kind: ConfigMap
apiVersion: v1
metadata:
  name: kiali
  namespace: aks-istio-system
  uid: 9ca2d6af-b69e-431c-815d-d36ae4a24b7b
  resourceVersion: '1332113'
  creationTimestamp: '2024-10-01T12:46:29Z'
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.89.7
    version: v1.89.7
  ownerReferences:
    - apiVersion: kiali.io/v1alpha1
      kind: Kiali
      name: kiali
      uid: f2aa3fde-69c1-438d-8c8c-4f902d1780ef
  managedFields:
    - manager: OpenAPI-Generator
      operation: Update
      apiVersion: v1
      time: '2024-10-15T09:32:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:version: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"f2aa3fde-69c1-438d-8c8c-4f902d1780ef"}: {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-10-15T10:05:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:config.yaml: {}
data:
  config.yaml: |
    additional_display_details:
    - annotation: kiali.io/api-spec
      icon_annotation: kiali.io/api-type
      title: API Documentation
    api:
      namespaces:
        exclude:
        - ^istio-operator
        - ^kube-.*
        - ^openshift.*
        - ^ibm.*
        - ^kiali-operator
        include: []
        label_selector_exclude: ''
    auth:
      openid:
        additional_request_params: {}
        allowed_domains: []
        api_proxy: ''
        api_proxy_ca_data: ''
        api_token: id_token
        authentication_timeout: 300
        authorization_endpoint: ''
        client_id: ''
        disable_rbac: false
        http_proxy: ''
        https_proxy: ''
        insecure_skip_verify_tls: false
        issuer_uri: ''
        scopes:
        - openid
        - profile
        - email
        username_claim: sub
      openshift: null
      strategy: token
    clustering:
      autodetect_secrets:
        enabled: true
        label: kiali.io/multiCluster=true
      clusters: []
      kiali_urls: []
    custom_dashboards: []
    deployment:
      accessible_namespaces:
      - '**'
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      cluster_wide_access: true
      configmap_annotations: {}
      custom_secrets: []
      dns:
        config: {}
        policy: ''
      host_aliases: []
      hpa:
        api_version: autoscaling/v2
        spec: {}
      image_digest: ''
      image_name: quay.io/kiali/kiali
      image_pull_policy: IfNotPresent
      image_pull_secrets: []
      image_version: v1.89.7
      ingress:
        additional_labels: {}
        class_name: nginx
        enabled: false
      instance_name: kiali
      logger:
        log_format: text
        log_level: info
        sampler_rate: '1'
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: aks-istio-system
      node_selector: {}
      pod_annotations: {}
      pod_labels: {}
      priority_class_name: ''
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
      secret_name: kiali
      security_context: {}
      service_annotations: {}
      tolerations: []
      version_label: v1.89.7
      view_only_mode: false
    external_services:
      custom_dashboards:
        discovery_auto_threshold: 10
        discovery_enabled: auto
        enabled: true
        is_core: false
        namespace_label: ''
        prometheus:
          auth:
            ca_file: ''
            insecure_skip_verify: false
            password: ''
            token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1jN2wzSXo5M2c3dXdnTmVFbW13X1dZR1BrbyIsImtpZCI6Ik1jN2wzSXo5M2c3dXdnTmVFbW13X1dZR1BrbyJ9.eyJhdWQiOiJodHRwczovL3Byb21ldGhldXMubW9uaXRvci5henVyZS5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNjg3YjYzMDMtZDBiYS00NWQzLWI0ZmQtZGFlYjgyNjJlMzNmLyIsImlhdCI6MTcyODk4NDk1NCwibmJmIjoxNzI4OTg0OTU0LCJleHAiOjE3Mjg5ODkwMzksImFjciI6IjEiLCJhaW8iOiJBWVFBZS84WUFBQUEvQ1RtQWZZenEyMjdIamtOK05CcXVPc3VNNFdYNHNvT0NDUWxnbzNWRWl5TEE0UWxic2VsN0ovTHdBM2Z5NGZBTFBTdC9ZdlhBbzhKWlBBcmNvVVJ4UmpnL2c2VC9YS1dyaXpEUENiU1BHWWlTeDNhdGJJWGZzL3pvd0JSU0J0T081dU9oNG9LYUhNVE5PSFIyVWtkYVR4dzNwT3J1QVUxK1I0TENhS05FdUU9IiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDM0MDAxNkQ1Qjg3NTYiLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJjYXJsb19yYW5kb25lQGl0LmlibS5jb20iLCJmYW1pbHlfbmFtZSI6IlJhbmRvbmUiLCJnaXZlbl9uYW1lIjoiQ2FybG8iLCJncm91cHMiOlsiN2Y2ZDM0MTItMjU0ZC00ZmNlLThmNzAtMWNmYTZjNWE4OTMyIl0sImlkcCI6ImxpdmUuY29tIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiNzkuNTAuMjAwLjc2IiwibmFtZSI6IkNhcmxvIFJhbmRvbmUiLCJvaWQiOiIzZmI1OTUyOC04NDYzLTRkNGYtYTM5Ni00YmZjZmRkYWViYjEiLCJwdWlkIjoiMTAwMzIwMDM2MkZCNEUwRSIsInJoIjoiMC5BYThBQTJON2FMclEwMFcwX2RycmdtTGpQMzZfRkw2MGlyQkpuY2FnN2QxdnB6NGRBWEUuIiwic2NwIjoiRGF0YS5SZWFkIiwic3ViIjoiVjlwaTh1V1BEM0hFRXI5TzNfRm1SbU92VGtqYVVaUEZoUzJoSkx5eWJvVSIsInRpZCI6IjY4N2I2MzAzLWQwYmEtNDVkMy1iNGZkLWRhZWI4MjYyZTMzZiIsInVuaXF1ZV9uYW1lIjoibGl2ZS5jb20jY2FybG9fcmFuZG9uZUBpdC5pYm0uY29tIiwidXRpIjoiT0d1cC1KT0NhMEs5a0RDZkxrc2pBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgMjYifQ.sEc0a_RKBIjXuQksvbtqj-bngQzOrfyazvBX9Oo89nf-cuFixtIVMek-rce_7ora-WFYbDBeeJwEdIs-nRO9NIgH4MdDVwWZhrf0vaHHB9IlIebIQihENmDrPx-0epFKZbqOxcZkqL-H-NYg8ztkrhZIkumQATPcKnJwJHYsBBe4EZdFsTg_6OzUXWyS6KH4NyAjREaAn3KfAjTNcnUnG0uKTM-z7YhtTWfrIo74V32EfCQgkUzqLl7Pn3oDPZAMnHmYP6HlcSWKBhNjR9zNCcs2SU-vRzF0JirLm1-6suBismdfVtbq0V_B1IsG_1AAnX55oTK2vTVEcaNA_nzWrQ'
            type: bearer
            use_kiali_token: false
            username: ''
          cache_duration: 7
          cache_enabled: true
          cache_expiration: 300
          custom_headers: {}
          health_check_url: 'http://172.214.59.63'
          is_core: true
          query_scope: {}
          thanos_proxy:
            enabled: false
            retention_period: 7d
            scrape_interval: 30s
          url: 'https://defaultazuremonitorworkspace-eus-g9bahme3f2c0aqc2.eastus.prometheus.monitor.azure.com'
      grafana:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        - name: Istio Mesh Dashboard
        - name: Istio Control Plane Dashboard
        - name: Istio Performance Dashboard
        - name: Istio Wasm Extension Dashboard
        enabled: false
        health_check_url: ''
        in_cluster_url: http://grafana.aks-istio-system:3000
        is_core: false
        url: ''
      istio:
        component_status:
          components:
          - app_label: istiod
            is_core: true
            is_proxy: false
            namespace: 'aks-istio-system'
          - app_label: istio-ingressgateway
            is_core: true
            is_proxy: true
            namespace: 'aks-istio-ingress'
          - app_label: istio-egressgateway
            is_core: false
            is_proxy: true
            namespace: 'aks-istio-egress'
          enabled: true
        config_map_name: istio-asm-1-23
        envoy_admin_local_port: 15000
        gateway_api_classes: []
        istio_api_enabled: true
        istio_identity_domain: svc.cluster.local
        istio_injection_annotation: sidecar.istio.io/inject
        istio_sidecar_annotation: sidecar.istio.io/status
        istio_sidecar_injector_config_map_name: istio-sidecar-injector
        istiod_deployment_name: istio-asm-1-23
        istiod_pod_monitoring_port: 15014
        root_namespace: aks-istio-system
        url_service_version: http://istiod.aks-istio-system:15014/version
      prometheus:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1jN2wzSXo5M2c3dXdnTmVFbW13X1dZR1BrbyIsImtpZCI6Ik1jN2wzSXo5M2c3dXdnTmVFbW13X1dZR1BrbyJ9.eyJhdWQiOiJodHRwczovL3Byb21ldGhldXMubW9uaXRvci5henVyZS5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNjg3YjYzMDMtZDBiYS00NWQzLWI0ZmQtZGFlYjgyNjJlMzNmLyIsImlhdCI6MTcyODk4NDk1NCwibmJmIjoxNzI4OTg0OTU0LCJleHAiOjE3Mjg5ODkwMzksImFjciI6IjEiLCJhaW8iOiJBWVFBZS84WUFBQUEvQ1RtQWZZenEyMjdIamtOK05CcXVPc3VNNFdYNHNvT0NDUWxnbzNWRWl5TEE0UWxic2VsN0ovTHdBM2Z5NGZBTFBTdC9ZdlhBbzhKWlBBcmNvVVJ4UmpnL2c2VC9YS1dyaXpEUENiU1BHWWlTeDNhdGJJWGZzL3pvd0JSU0J0T081dU9oNG9LYUhNVE5PSFIyVWtkYVR4dzNwT3J1QVUxK1I0TENhS05FdUU9IiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDM0MDAxNkQ1Qjg3NTYiLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJjYXJsb19yYW5kb25lQGl0LmlibS5jb20iLCJmYW1pbHlfbmFtZSI6IlJhbmRvbmUiLCJnaXZlbl9uYW1lIjoiQ2FybG8iLCJncm91cHMiOlsiN2Y2ZDM0MTItMjU0ZC00ZmNlLThmNzAtMWNmYTZjNWE4OTMyIl0sImlkcCI6ImxpdmUuY29tIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiNzkuNTAuMjAwLjc2IiwibmFtZSI6IkNhcmxvIFJhbmRvbmUiLCJvaWQiOiIzZmI1OTUyOC04NDYzLTRkNGYtYTM5Ni00YmZjZmRkYWViYjEiLCJwdWlkIjoiMTAwMzIwMDM2MkZCNEUwRSIsInJoIjoiMC5BYThBQTJON2FMclEwMFcwX2RycmdtTGpQMzZfRkw2MGlyQkpuY2FnN2QxdnB6NGRBWEUuIiwic2NwIjoiRGF0YS5SZWFkIiwic3ViIjoiVjlwaTh1V1BEM0hFRXI5TzNfRm1SbU92VGtqYVVaUEZoUzJoSkx5eWJvVSIsInRpZCI6IjY4N2I2MzAzLWQwYmEtNDVkMy1iNGZkLWRhZWI4MjYyZTMzZiIsInVuaXF1ZV9uYW1lIjoibGl2ZS5jb20jY2FybG9fcmFuZG9uZUBpdC5pYm0uY29tIiwidXRpIjoiT0d1cC1KT0NhMEs5a0RDZkxrc2pBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgMjYifQ.sEc0a_RKBIjXuQksvbtqj-bngQzOrfyazvBX9Oo89nf-cuFixtIVMek-rce_7ora-WFYbDBeeJwEdIs-nRO9NIgH4MdDVwWZhrf0vaHHB9IlIebIQihENmDrPx-0epFKZbqOxcZkqL-H-NYg8ztkrhZIkumQATPcKnJwJHYsBBe4EZdFsTg_6OzUXWyS6KH4NyAjREaAn3KfAjTNcnUnG0uKTM-z7YhtTWfrIo74V32EfCQgkUzqLl7Pn3oDPZAMnHmYP6HlcSWKBhNjR9zNCcs2SU-vRzF0JirLm1-6suBismdfVtbq0V_B1IsG_1AAnX55oTK2vTVEcaNA_nzWrQ'
          type: bearer
          use_kiali_token: false
          username: ''
        cache_duration: 7
        cache_enabled: true
        cache_expiration: 300
        custom_headers: {}
        health_check_url: 'http://172.214.59.63'
        is_core: true
        query_scope: {}
        thanos_proxy:
          enabled: false
          retention_period: 7d
          scrape_interval: 30s
        url: 'https://defaultazuremonitorworkspace-eus-g9bahme3f2c0aqc2.eastus.prometheus.monitor.azure.com'
      tracing:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        custom_headers: {}
        enabled: false
        grpc_port: 9095
        health_check_url: ''
        in_cluster_url: http://tracing.aks-istio-system:16685/jaeger
        is_core: false
        namespace_selector: true
        provider: jaeger
        query_scope: {}
        query_timeout: 5
        tempo_config:
          datasource_uid: ''
          org_id: ''
        url: ''
        use_grpc: true
        whitelist_istio_system:
        - jaeger-query
        - istio-ingressgateway
    health_config:
      rate: []
    identity:
      cert_file: ''
      private_key_file: ''
    installation_tag: ''
    istio_labels:
      app_label_name: app
      injection_label_name: istio-injection
      injection_label_rev: istio.io/rev
      version_label_name: version
    istio_namespace: aks-istio-system
    kiali_feature_flags:
      certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
      disabled_features: []
      istio_annotation_action: true
      istio_injection_action: true
      istio_upgrade_action: false
      ui_defaults:
        graph:
          find_options:
          - auto_select: false
            description: 'Find: slow edges (> 1s)'
            expression: rt > 1000
          - auto_select: false
            description: 'Find: unhealthy nodes'
            expression: '! healthy'
          - auto_select: false
            description: 'Find: unknown nodes'
            expression: name = unknown
          - auto_select: false
            description: 'Find: nodes with the 2 top rankings'
            expression: rank <= 2
          hide_options:
          - auto_select: false
            description: 'Hide: healthy nodes'
            expression: healthy
          - auto_select: false
            description: 'Hide: unknown nodes'
            expression: name = unknown
          - auto_select: false
            description: 'Hide: nodes ranked lower than the 2 top rankings'
            expression: rank > 2
          settings:
            font_label: 13
            min_font_badge: 7
            min_font_label: 10
          traffic:
            grpc: requests
            http: requests
            tcp: sent
        list:
          include_health: true
          include_istio_resources: true
          include_validations: true
          show_include_toggles: false
        metrics_inbound:
          aggregations: []
        metrics_outbound:
          aggregations: []
        metrics_per_refresh: 1m
        namespaces: []
        refresh_interval: 60s
      validations:
        ignore:
        - KIA1301
        skip_wildcard_gateway_hosts: false
    kubernetes_config:
      burst: 200
      cache_duration: 300
      cache_token_namespace_duration: 10
      cluster_name: ''
      excluded_workloads:
      - CronJob
      - DeploymentConfig
      - Job
      - ReplicationController
      qps: 175
    login_token:
      expiration_seconds: 86400
      signing_key: secret:kiali-signing-key:key
    server:
      address: ''
      audit_log: true
      cors_allow_all: false
      gzip_enabled: true
      observability:
        metrics:
          enabled: true
          port: 9090
        tracing:
          collector_type: jaeger
          collector_url: http://jaeger-collector.istio-system:14268/api/traces
          enabled: false
          otel:
            ca_name: ''
            protocol: http
            skip_verify: false
            tls_enabled: false
      port: 20001
      profiler:
        enabled: false
      web_fqdn: ''
      web_history_mode: ''
      web_port: ''
      web_root: /kiali
      web_schema: ''
      write_timeout: 30
    version: default
